# Generated by Django 5.2.8 on 2025-12-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255, verbose_name="موضوع ویدیو")),
                (
                    "script_text",
                    models.TextField(blank=True, verbose_name="متن اسکریپت"),
                ),
                (
                    "audio_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="آدرس فایل صدا",
                    ),
                ),
                (
                    "video_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="آدرس فایل ویدیو",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس (خام)"),
                            ("script_ready", "اسکریپت آماده"),
                            ("audio_ready", "صدا تولید شده"),
                            ("video_ready", "ویدیو نهایی ساخته شده"),
                            ("uploaded", "آپلود شده در یوتیوب"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت پروژه",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "پروژه ویدیویی",
                "verbose_name_plural": "پروژه\u200cهای ویدیویی",
            },
        ),
    ]
