# Generated by Django 5.2.8 on 2025-12-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_engine", "0002_videoproject_content_style_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoproject",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="content_style",
            field=models.CharField(
                choices=[
                    ("Detailed_Explanation", "توضیح جزئیات کامل"),
                    ("Quick_Summary", "خلاصه سریع"),
                    ("Problem_Solving", "حل مسئله"),
                    ("Conceptual_Focus", "تمرکز مفهومی"),
                ],
                default="Detailed_Explanation",
                max_length=50,
                verbose_name="سبک تولید محتوا",
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="scheduled_publish_time",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="زمان برنامه\u200cریزی شده برای انتشار",
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="script_text",
            field=models.TextField(blank=True, verbose_name="متن اسکریپت"),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس (خام)"),
                    ("script_ready", "اسکریپت آماده"),
                    ("audio_ready", "صدا تولید شده"),
                    ("video_ready", "ویدیو نهایی ساخته شده"),
                    ("uploaded", "آپلود شده در یوتیوب"),
                ],
                default="draft",
                max_length=20,
                verbose_name="وضعیت پروژه",
            ),
        ),
    ]
