# Generated by Django 5.2.8 on 2025-12-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_engine", "0003_remove_videoproject_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoproject",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="content_style",
            field=models.CharField(
                choices=[
                    ("Detailed_Explanation", "توضیح کامل و جامع"),
                    ("Quick_Summary", "خلاصه سریع و نکات کلیدی"),
                    ("Problem_Solving", "آموزش از طریق حل مسئله"),
                    ("Conceptual_Focus", "تمرکز بر مفاهیم و تعریف\u200cها"),
                ],
                default="Detailed_Explanation",
                max_length=50,
                verbose_name="سبک محتوا (انعطاف پرامپت)",
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="scheduled_publish_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمان انتشار برنامه ریزی شده"
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="script_text",
            field=models.TextField(blank=True, verbose_name="متن سناریو"),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "پیش نویس"),
                    ("script_ready", "متن آماده"),
                    ("audio_ready", "صوت آماده"),
                    ("video_ready", "ویدیو آماده"),
                    ("uploaded", "آپلود شده"),
                    ("scheduled", "زمان بندی شده"),
                ],
                default="draft",
                max_length=20,
                verbose_name="وضعیت پروژه",
            ),
        ),
    ]
