# Generated by Django 5.2.8 on 2025-12-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_engine", "0004_videoproject_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoproject",
            name="content_style",
        ),
        migrations.RemoveField(
            model_name="videoproject",
            name="scheduled_publish_time",
        ),
        migrations.RemoveField(
            model_name="videoproject",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="videoproject",
            name="thumbnail_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="آدرس فایل کاور"
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="script_text",
            field=models.TextField(blank=True, verbose_name="متن اسکریپت"),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس (خام)"),
                    ("script_ready", "اسکریپت آماده"),
                    ("audio_ready", "صدا تولید شده"),
                    ("video_ready", "ویدیو نهایی ساخته شده"),
                    ("uploaded", "آپلود شده در یوتیوب"),
                ],
                default="draft",
                max_length=50,
                verbose_name="وضعیت پروژه",
            ),
        ),
    ]
