# Generated by Django 5.2.8 on 2025-12-05 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_engine", "0005_remove_videoproject_content_style_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videoproject",
            options={},
        ),
        migrations.RemoveField(
            model_name="videoproject",
            name="audio_path",
        ),
        migrations.AddField(
            model_name="videoproject",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("topic_based", "بر اساس موضوع (متن)"),
                    ("image_based", "بر اساس تصاویر (اسلاید)"),
                ],
                default="topic_based",
                max_length=20,
                verbose_name="نوع پروژه",
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="script_text",
            field=models.TextField(blank=True, verbose_name="متن کل سناریو"),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("script_ready", "اسکریپت آماده"),
                    ("audio_ready", "صدا تولید شده"),
                    ("video_ready", "ویدیو نهایی ساخته شده"),
                    ("uploaded", "آپلود شده در یوتیوب"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="thumbnail_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="topic",
            field=models.CharField(max_length=255, verbose_name="عنوان پروژه"),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="video_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="user_uploads/", verbose_name="فایل تصویر"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="توضیح هوش مصنوعی برای این عکس"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content_engine.videoproject",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
