# Generated by Django 5.2.8 on 2025-12-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_engine", "0006_alter_videoproject_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoproject",
            name="narrator_style",
            field=models.CharField(
                choices=[
                    ("math", "👨\u200d🏫 معلم ریاضی (تخصصی)"),
                    ("story", "📖 داستان\u200cگو (خلاقانه)"),
                    ("business", "👔 رسمی و بیزنس (توضیحی)"),
                    ("general", "🕵️ عمومی (توصیف ساده)"),
                ],
                default="general",
                max_length=20,
                verbose_name="سبک روایت",
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(upload_to="user_uploads/"),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("topic_based", "بر اساس موضوع (متن)"),
                    ("image_based", "بر اساس تصاویر (اسلاید)"),
                ],
                default="topic_based",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="script_text",
            field=models.TextField(blank=True),
        ),
    ]
