# Generated by Django 5.2.8 on 2025-12-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_engine", "0007_videoproject_narrator_style_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videoproject",
            options={
                "verbose_name": "پروژه ویدیویی",
                "verbose_name_plural": "پروژه\u200cهای ویدیویی",
            },
        ),
        migrations.AddField(
            model_name="videoproject",
            name="audio_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="duration_type",
            field=models.CharField(
                choices=[
                    ("short", "کوتاه (۱ تا ۲ دقیقه)"),
                    ("medium", "متوسط (۳ تا ۵ دقیقه)"),
                    ("long", "طولانی و جامع (۵ تا ۱۰ دقیقه)"),
                ],
                default="short",
                max_length=20,
                verbose_name="مدت زمان",
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                upload_to="user_uploads/", verbose_name="فایل تصویر"
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("topic_based", "بر اساس موضوع (متن)"),
                    ("image_based", "بر اساس تصاویر (اسلاید)"),
                ],
                default="topic_based",
                max_length=20,
                verbose_name="نوع پروژه",
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="script_text",
            field=models.TextField(blank=True, verbose_name="متن کل سناریو"),
        ),
    ]
