# Generated by Django 5.2.8 on 2025-12-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_engine",
            "0008_alter_videoproject_options_videoproject_audio_path_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="videoproject",
            name="generated_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="توضیحات یوتیوب"
            ),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="generated_tags",
            field=models.TextField(blank=True, null=True, verbose_name="تگ\u200cها"),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="generated_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="تایتل یوتیوب"
            ),
        ),
    ]
