# Generated by Django 5.2.8 on 2025-12-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_engine", "0009_videoproject_generated_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoproject",
            name="scheduled_creation",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمان شروع ساخت"
            ),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="scheduled_upload",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمان آپلود"
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="generated_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="generated_tags",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="generated_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
