# Generated by Django 5.2.8 on 2025-12-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_engine", "0010_videoproject_scheduled_creation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoproject",
            name="platform",
            field=models.CharField(
                choices=[
                    ("youtube", "YouTube"),
                    ("telegram", "Telegram"),
                    ("instagram", "Instagram"),
                    ("twitter", "X (Twitter)"),
                    ("tiktok", "TikTok"),
                ],
                default="youtube",
                max_length=20,
                verbose_name="پلتفرم انتشار",
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="script_text",
            field=models.TextField(blank=True, null=True, verbose_name="متن سناریو"),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("script_ready", "اسکریپت آماده"),
                    ("audio_ready", "صدا تولید شده"),
                    ("video_ready", "ویدیو نهایی ساخته شده"),
                    ("uploaded", "آپلود شده در برنامه"),
                ],
                default="draft",
                max_length=50,
                verbose_name="وضعیت فعلی",
            ),
        ),
    ]
