# Generated by Django 5.2.8 on 2025-12-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_engine",
            "0011_videoproject_platform_alter_videoproject_script_text_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramProject",
            fields=[],
            options={
                "verbose_name": "ریلز اینستاگرام",
                "verbose_name_plural": "📸 مدیریت اینستاگرام",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content_engine.videoproject",),
        ),
        migrations.CreateModel(
            name="TelegramProject",
            fields=[],
            options={
                "verbose_name": "پست تلگرام",
                "verbose_name_plural": "✈️ مدیریت تلگرام",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content_engine.videoproject",),
        ),
        migrations.CreateModel(
            name="YouTubeProject",
            fields=[],
            options={
                "verbose_name": "ویدیو یوتیوب",
                "verbose_name_plural": "🔴 مدیریت یوتیوب",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content_engine.videoproject",),
        ),
        migrations.AlterModelOptions(
            name="videoproject",
            options={
                "verbose_name": "همه پروژه\u200cها (کلی)",
                "verbose_name_plural": "📂 آرشیو کل پروژه\u200cها",
            },
        ),
        migrations.AddField(
            model_name="videoproject",
            name="brand_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="برند محصول"
            ),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="discount_percent",
            field=models.PositiveIntegerField(default=0, verbose_name="درصد تخفیف"),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="original_price",
            field=models.PositiveIntegerField(
                default=0, verbose_name="قیمت اصلی (تومان)"
            ),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="shipping_info",
            field=models.CharField(
                default="3 تا 5 روز کاری", max_length=100, verbose_name="زمان ارسال"
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="duration_type",
            field=models.CharField(
                choices=[("short", "کوتاه"), ("medium", "متوسط")],
                default="short",
                max_length=20,
                verbose_name="مدت زمان",
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="narrator_style",
            field=models.CharField(
                choices=[
                    ("math", "👨\u200d🏫 معلم ریاضی"),
                    ("story", "📖 داستان\u200cگو"),
                    ("business", "👔 رسمی و بیزنس"),
                    ("general", "🕵️ عمومی"),
                    ("sales", "💰 بازاریاب حرفه\u200cای"),
                ],
                default="sales",
                max_length=20,
                verbose_name="سبک روایت",
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="platform",
            field=models.CharField(
                choices=[
                    ("youtube", "YouTube"),
                    ("telegram", "Telegram"),
                    ("instagram", "Instagram"),
                    ("twitter", "X (Twitter)"),
                    ("tiktok", "TikTok"),
                ],
                default="telegram",
                max_length=20,
                verbose_name="پلتفرم انتشار",
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("topic_based", "ویدیو/متن معمولی"),
                    ("image_based", "ویدیو اسلایدی"),
                    ("product_post", "🛍️ پست محصول (فروشگاهی)"),
                ],
                default="product_post",
                max_length=20,
                verbose_name="نوع پروژه",
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="script_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="متن کپشن/سناریو"
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("script_ready", "محتوا آماده"),
                    ("video_ready", "تصویر/ویدیو آماده"),
                    ("uploaded", "آپلود شده"),
                ],
                default="draft",
                max_length=50,
                verbose_name="وضعیت فعلی",
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="topic",
            field=models.CharField(max_length=255, verbose_name="عنوان محصول / موضوع"),
        ),
    ]
