# Generated by Django 5.2.8 on 2025-12-16 14:57

import apps.content_engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_engine",
            "0012_instagramproject_telegramproject_youtubeproject_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                upload_to=apps.content_engine.models.get_upload_path,
                verbose_name="فایل تصویر",
            ),
        ),
    ]
